"""Add AuditLog model

Revision ID: 6158f44dafca
Revises: 0019
Create Date: 2026-05-28 01:37:59.901979

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

revision: str = '6158f44dafca'
down_revision: Union[str, None] = '0019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ff_audit_log',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ff_audit_log_action'), 'ff_audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_ff_audit_log_timestamp'), 'ff_audit_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_ff_audit_log_username'), 'ff_audit_log', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ff_audit_log_username'), table_name='ff_audit_log')
    op.drop_index(op.f('ix_ff_audit_log_timestamp'), table_name='ff_audit_log')
    op.drop_index(op.f('ix_ff_audit_log_action'), table_name='ff_audit_log')
    op.drop_table('ff_audit_log')
    # ### end Alembic commands ###
