"""Add send_only_on_failure to ff_pipelines

Revision ID: 9c08f36f9ef8
Revises: b7a76582c1ea
Create Date: 2026-05-30 10:19:08.918159

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


revision: str = '9c08f36f9ef8'
down_revision: Union[str, None] = 'b7a76582c1ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ff_pipelines', sa.Column('send_only_on_failure', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ff_pipelines', 'send_only_on_failure')
    # ### end Alembic commands ###
