"""Add SSHConnection and update step_type constraint

Revision ID: b7a76582c1ea
Revises: 6158f44dafca
Create Date: 2026-05-30 10:14:27.311660

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'b7a76582c1ea'
down_revision: str | None = '6158f44dafca'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_NEW_TYPES = (
    "'db_procedure','db_query','report','email','drive_upload',"
    "'data_load','bulk_load','onedrive_upload','ai_analyze','sftp_transfer',"
    "'ssh_command','db_health_check','data_report'"
)
_OLD_TYPES = (
    "'db_procedure','db_query','report','email','drive_upload',"
    "'data_load','bulk_load','onedrive_upload','ai_analyze','sftp_transfer'"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ff_ssh_connections',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    op.drop_constraint('ck_step_type', 'ff_pipeline_steps')
    op.create_check_constraint(
        'ck_step_type',
        'ff_pipeline_steps',
        f'step_type IN ({_NEW_TYPES})',
    )


def downgrade() -> None:
    op.drop_constraint('ck_step_type', 'ff_pipeline_steps')
    op.create_check_constraint(
        'ck_step_type',
        'ff_pipeline_steps',
        f'step_type IN ({_OLD_TYPES})',
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ff_ssh_connections')
    # ### end Alembic commands ###

